FROM node:18.16.0-alpine AS build

WORKDIR /app

COPY package.json package-lock.json /app/
RUN npm ci --quiet
COPY . /app/
RUN npm run build

# Production stage
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]