services:
  backend_agenda:
    image: iocio005/backend_agenda:latest
    environment:
      - USE_DOCKER=yes
      - ALLOWED_ORIGINS=http://localhost:8080
    ports:
      - "5000:5000"

  frontend_agenda:
    image: iocio005/frontend_agenda:latest
    environment:
      - USE_DOCKER=yes
    ports:
      - "8080:80"
