# Etapa de compilación
FROM node:18.16.0-alpine AS build

WORKDIR /app

COPY package.json package-lock.json /app/
RUN npm ci --quiet
COPY . /app/
RUN npm run build

FROM node:18.16.0-alpine

WORKDIR /app

COPY --from=build /app/package.json /app/package-lock.json /app/
COPY --from=build /app/.next /app/.next
COPY --from=build /app/public /app/public

RUN npm ci --production --quiet

EXPOSE 3000

CMD ["npm", "start"]
