services:
  backend_agenda:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: iocio005/backend_agenda:latest
    container_name: backend_agenda
    environment:
      - USE_DOCKER=yes
      - ALLOWED_ORIGINS=http://localhost:8080
    ports:
      - "5000:80"

  frontend_agenda:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: iocio005/frontend_agenda:latest
    container_name: frontend_agenda
    volumes:
      - ./frontend:/app:z
    environment:
      - USE_DOCKER=yes
    ports:
      - "8080:80"
