services:
  backend_agenda:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_agenda
    #volumes:
    #  - ./backend/app:/app:z
    environment:
      - USE_DOCKER=yes
      - ALLOWED_ORIGINS=http://frontend_agenda:3000,http://localhost:3000 # Cors updated to let Cypress make requests
      - DB_DEFAULT_USER=user
      - DB_DEFAULT_PASS=user
    ports:
      - "5000:80"

  frontend_agenda:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: frontend_agenda
    container_name: frontend_agenda
    #volumes:
    #  - ./frontend:/app:z
    environment:
      - USE_DOCKER=yes
      #- REACT_APP_API_URL=http://backend_agenda:80/ # Port 80 because we are hitting to container directly, not host
      - REACT_APP_API_URL=http://localhost:5000/ # Port 80 because we are hitting to container directly, not host
    depends_on:
      - backend_agenda
    ports:
      - "3000:80"

  cypress:
    build:
      context: ./frontend/e2e
      dockerfile: ./Dockerfile.test
    image: cypress_test_agenda
    environment:
      CYPRESS_baseUrl: "http://frontend_agenda:3000"
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/e2e:/app
    depends_on:
      - frontend_agenda
    command: npx cypress run --headless --browser chrome
