services:
  backend_agenda:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_agenda
    volumes:
      - ./backend/app:/app:z
    environment:
      - USE_DOCKER=yes
      - ALLOWED_ORIGINS=http://localhost:3000
      - APP_VERSION=2.2.2
    ports:
      - "5000:80"

  frontend_agenda:
    build: ./frontend
    image: frontend_agenda
    container_name: frontend_agenda
    volumes:
      - ./frontend:/app:z
    environment:
      - USE_DOCKER=yes
    ports:
      - "3000:3000"
