services:
  backend_agenda:
    image: iocio005/backend_agenda:latest
    environment:
      - USE_DOCKER=yes
      - ALLOWED_ORIGINS=https://agenda.ikerocio.com,http://35.180.123.117:5000
    ports:
      - "5000:80"

  frontend_agenda:
    image: iocio005/frontend_agenda:latest
    environment:
      - USE_DOCKER=yes
    ports:
      - "8080:80"
