services:
  nextjs_agenda:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: iocio005/nextjs_agenda:latest
    container_name: nextjs_agenda
    volumes:
      - ./:/app:z
    environment:
      - "USE_DOCKER=yes"
    ports:
      - "3000:3000"
