name: Deploy to Server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:23.0-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare env files
        run: |
          current_date=$(date +'%y.%m.%d-%H%M%S')
          echo REACT_APP_API_URL=https://agenda-back.ikerocio.com/ > ./frontend/.env.local
          echo REACT_APP_VERSION=$current_date >> ./frontend/.env.local
          echo APP_VERSION=$current_date > ./backend/.env

      - name: E2E tests
        run: |
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit cypress
        if: ${{ success() }}

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: e2e screenshots
          path: frontend/e2e/cypress/screenshots/*
        if: ${{ always() }}

      - name: Upload videos
        uses: actions/upload-artifact@v3
        with:
          name: e2e videos
          path: frontend/e2e/cypress/videos/*
        if: ${{ always() }}

      - name: Build and push Docker Compose
        run: |
          docker-compose -f docker-compose.build.yml build
          docker-compose -f docker-compose.build.yml push
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.IKEROCIOCOM_LIGHTSAIL_SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 35.180.123.117 >> ~/.ssh/known_hosts

      - name: Deploy code
        run: |
          ssh ec2-user@35.180.123.117 "cd agenda && docker-compose stop && docker-compose pull && docker-compose up -d"
