name: Merge to master
on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:23.0-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: E2E tests
        run: |
          docker-compose -f docker-compose.test.yml up
